name: PHPUnit

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    env:
      extensions: amqp apcu gettext igbinary intl mbstring memcached xdebug

    strategy:
      matrix:
        include:
          - php: '7.4'
            phpunit: 'latest'
          - php: '8.0'
            phpunit: 'latest'
          - php: '8.1'
            phpunit: 'latest'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: php-actions/composer@v6
        with:
          memory_limit: 256M
          php_version: "${{ matrix.php }}"
          php_extensions: "${{ env.extensions }}"

      - name: Run Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          args: --coverage-text
          memory_limit: 256M
          bootstrap: ./vendor/autoload.php
          version: "${{ matrix.phpunit }}"
          php_version: "${{ matrix.php }}"
          php_extensions: "${{ env.extensions }}"
